name: Build and Deploy to NuGet

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'  # Or your project's .NET version

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Push to NuGet
      run: dotnet nuget push '**/*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
