name: Build and Deploy to NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Project with MSBuild
      run: msbuild /p:Configuration=Release

    - name: Push to NuGet
      run: dotnet nuget push '**/*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
